# Generated by Django 3.2.9 on 2021-12-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0002_auto_20211203_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
