# Generated by Django 3.2.9 on 2021-12-05 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0003_alter_election_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 17, 2, 37, 291266)),
        ),
    ]
