# Generated by Django 3.2.9 on 2021-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0005_alter_forecast_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
