# Generated by Django 3.2.9 on 2021-12-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0007_auto_20211206_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='alp_overall_win_pc',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='forecast',
            name='lnp_overall_win_pc',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='forecast',
            name='oth_overall_win_pc',
            field=models.FloatField(default=0),
        ),
    ]
