# Generated by Django 3.2.9 on 2021-12-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0008_auto_20211206_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='report',
            field=models.JSONField(default=str),
        ),
    ]
