# Generated by Django 3.2.9 on 2021-12-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0009_forecast_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='alp_overall_win_pc',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='description',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='lnp_overall_win_pc',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='oth_overall_win_pc',
        ),
    ]
