# Generated by Django 3.2.9 on 2022-02-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0010_auto_20211216_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='flags',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='forecast',
            name='label',
            field=models.CharField(default='', max_length=256),
        ),
    ]
