# Generated by Django 3.2.9 on 2022-02-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0011_auto_20220213_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='flags',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
