# Generated by Django 3.2.9 on 2022-06-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0014_auto_20220327_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='results',
            field=models.JSONField(default=str),
        ),
        migrations.AddField(
            model_name='election',
            name='results_version',
            field=models.IntegerField(default=0),
        ),
    ]
