export const STRIPE_PAYMENT_LINK_URL =
  process.env.REACT_APP_STRIPE_PAYMENT_LINK_URL || '';

export const STRIPE_BUY_BUTTON_ID =
  process.env.REACT_APP_STRIPE_BUY_BUTTON_ID || '';

export const STRIPE_PUBLISHABLE_KEY =
  process.env.REACT_APP_STRIPE_PUBLISHABLE_KEY || '';

export const DONATIONS_ENABLED = Boolean(
  STRIPE_PAYMENT_LINK_URL || (STRIPE_BUY_BUTTON_ID && STRIPE_PUBLISHABLE_KEY)
);
