# Generated by Django 3.2.9 on 2022-03-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentary_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='election',
            new_name='commentary',
        ),
    ]
