# Generated by Django 3.2.9 on 2022-03-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentary_api', '0003_auto_20220303_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
