# Generated by Django 3.2.9 on 2022-03-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentary_api', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
