# Generated by Django 3.2.9 on 2021-11-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_forecasts', 'View forecasts'),)},
        ),
    ]
